Hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('habitaciones/', include('habitaciones.urls',namespace='habitaciones')),
    path('eventos/', include('eventos.urls')),
    path('contacto/', include('contacto.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('restaurante/', include('restaurante.urls')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autenticacion/urls.py
from django.urls import path
from django.contrib import admin
from .views import RegistroView, perfil
from . import views


app_name = 'autenticacion'  # Agrega el namespace

urlpatterns = [
    path('registro/', RegistroView.as_view(), name='registro'),  # Este es un ejemplo, ajusta según tus URLs
    # Otras URLs...
]

habitaciones/urls.py
from django.contrib import admin
from django.urls import path
from .views import HabitacionView
from . import views

app_name='habitaciones'
urlpatterns = [
    path('', HabitacionView.as_view(), name="habitacion")
]

inicio/urls.py
from django.contrib import admin
from django.urls import path
from .views import InicioView

urlpatterns = [
    path('', InicioView.as_view(), name="inicio"),
]

inicio/models.py
from django.db import models

# Create your models here.

inicio/views.py
from django.shortcuts import render

from django.views.generic import TemplateView


class InicioView(TemplateView):
    template_name = "inicio/inicio.html"

inicio/templates/superior/barraNav.html
<!-- Barra de navegación con Bootstrap -->
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Katu Sukchij</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'inicio' %}">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'habitaciones:habitacion' %}">Habitaciones</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'restaurante' %}">Restaurante</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'eventos' %}">Eventos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contacto' %}">Contacto</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'autenticacion:registro' %}">Registro</a>
                </li>
            </ul>
            <img src="{% static 'img/logo.jpg' %}" alt="Logo del hotel" class="ml-3 img-logo-navbar">
        </div>
    </div>
</nav>